=== jweile/harness/src/main/resources/harness.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://cs.ncl.ac.uk/harness/protocol"
    elementFormDefault="qualified" xmlns:tns="http://cs.ncl.ac.uk/harness/protocol">
    <xsd:element name="protocol">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="variables" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="incrementalVariable" maxOccurs="unbounded" minOccurs="0">
                                <xsd:complexType>
                                    <xsd:attribute name="id" type="xsd:ID" use="required"/>
                                    <xsd:attribute name="min" type="xsd:double" use="required"/>
                                    <xsd:attribute name="max" type="xsd:double" use="required"/>
                                    <xsd:attribute name="inc" type="xsd:double" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="logarithmicVariable" minOccurs="0" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:attribute name="id" type="xsd:ID" use="required"/>
                                    <xsd:attribute name="range" type="xsd:string" use="required"/>
                                    <xsd:attribute name="iterations" type="xsd:int" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="graphImplementation">
                    <xsd:complexType>
                        <xsd:attribute name="type" type="xsd:string" use="required"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="graphPopulation">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="properties" type="tns:propertyListType"/>
                        </xsd:sequence>
                        <xsd:attribute name="type" type="xsd:string" use="required"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="integration">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="goldStandards" minOccurs="0" type="tns:experimentListType"></xsd:element>
                            <xsd:element name="evidentialGraphs" maxOccurs="1" type="tns:experimentListType"></xsd:element>
                            <xsd:element name="properties" minOccurs="0" type="tns:propertyListType"/>
                        </xsd:sequence>
                        <xsd:attribute name="type" type="xsd:string" use="required"/>
                        <xsd:attribute name="cycleReplicas" type="xsd:int"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="propertyListType">
        <xsd:sequence>
            <xsd:element name="staticProperty" maxOccurs="unbounded" minOccurs="0">
                <xsd:complexType>
                    <xsd:attribute name="key" type="xsd:string" use="required"/>
                    <xsd:attribute name="type" type="xsd:string" use="required"/>
                    <xsd:attribute name="value" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="variableProperty" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:attribute name="key" type="xsd:string" use="required"/>
                    <xsd:attribute name="type" type="xsd:string" use="required"/>
                    <xsd:attribute name="var-ref" type="xsd:IDREF" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="experimentListType">
        <xsd:sequence>
            <xsd:element name="experiment" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:choice>
                            <xsd:element name="variableReplicas">
                                <xsd:complexType>
                                    <xsd:attribute name="var-ref" type="xsd:IDREF" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="staticReplicas">
                                <xsd:complexType>
                                    <xsd:attribute name="value" type="xsd:int" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:choice>
                        <xsd:element name="properties" type="tns:propertyListType"/>
                    </xsd:sequence>
                    <xsd:attribute name="type" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== jweile/harness/src/test/resources/protocol.xml
<?xml version="1.0" encoding="UTF-8"?>

<protocol xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://cs.ncl.ac.uk/harness/protocol'
   xsi:schemaLocation='http://cs.ncl.ac.uk/harness/protocol harness.xsd'>

    <variables>
        <incrementalVariable id="replEv" min="3.0" max="5.0" inc="1.0"/>
    </variables>

    <graphImplementation type="mapgraph"/>

    <graphPopulation type="scalefree">
        <properties>
            <staticProperty key="seed" type="xsd:int" value="3"/>
            <staticProperty key="numNodes" type="xsd:int" value="500"/>
        </properties>
    </graphPopulation>

    <integration type="lycett" cycleReplicas="2">

        <goldStandards>
            <experiment type="simpleexperiment">
                <staticReplicas value="2"/>
                <properties>
                    <staticProperty key="sensitivity" type="xsd:double" value="0.9"/>
                    <staticProperty key="specificity" type="xsd:double" value="0.99"/>
                </properties>
            </experiment>
        </goldStandards>

        <evidentialGraphs>
            <experiment type="simpleexperiment">
                <variableReplicas var-ref="replEv"/>
                <properties>
                    <staticProperty key="sensitivity" type="xsd:double" value="0.9"/>
                    <staticProperty key="specificity" type="xsd:double" value="0.99"/>
                </properties>
            </experiment>
        </evidentialGraphs>

    </integration>

</protocol>

=== jweile/harness/src/test/resources/big_protocol.xml
<?xml version="1.0" encoding="UTF-8"?>

<xh:protocol  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:xh='http://cs.ncl.ac.uk/harness/protocol'
   xsi:schemaLocation='http://cs.ncl.ac.uk/harness/protocol harness.xsd'>
    <xh:variables>
<!--        <xh:incrementalVariable id="sensEv" min="0.9" max="0.99" inc="0.03"/>
        <xh:incrementalVariable id="sensGS" min="0.9" max="0.99" inc="0.03"/>-->
<!--        <xh:incrementalVariable id="replEv" min="2" max="5" inc="1"/>-->
<!--        <xh:incrementalVariable id="replGS" min="2" max="3" inc="1"/>-->
<!--        <xh:logarithmicVariable id="specEv" range="0-1" iterations="4"/>-->
<!--        <xh:logarithmicVariable id="specGS" range="0-1" iterations="4"/>-->
<!--        <xh:incrementalVariable id="leeThreshold" min="5.0" max="15" inc="0.5"/>-->
<!--        <xh:incrementalVariable id="dval" min="1.0" max="5.0" inc="0.1"/>-->
        <xh:incrementalVariable id="fprEv" min="0.1" max="0.9" inc="0.1"/>
    </xh:variables>
    <xh:graphImplementation type="mapgraph"/>
    <xh:graphPopulation type="scalefree">
        <xh:properties>
            <xh:staticProperty key="seed" type="xsd:int" value="3"/>
            <xh:staticProperty key="numNodes" type="xsd:int" value="500"/>
        </xh:properties>
    </xh:graphPopulation>
    <xh:integration type="lycett2" cycleReplicas="10">
        <xh:goldStandards>
            <xh:experiment type="fastexperiment">
<!--                <xh:variableReplicas var-ref="replGS"/>-->
                <xh:staticReplicas value="1"/>
<!--                    <xh:staticReplicas value="1"/>-->
                <xh:properties>
<!--                    <xh:variableProperty key="sensitivity" type="xsd:double" var-ref="sensGS"/>-->
                    <xh:staticProperty key="sensitivity" type="xsd:double" value="0.9"/>
<!--                    <xh:variableProperty key="specificity" type="xsd:double" var-ref="specGS"/>-->
                    <xh:staticProperty key="fpr" type="xsd:double" value="0.05"/>
                </xh:properties>
            </xh:experiment>
        </xh:goldStandards>
        <xh:evidentialGraphs>
            <xh:experiment type="fastexperiment">
<!--                <xh:variableReplicas var-ref="replEv"/>-->
                <xh:staticReplicas value="4"/>
                <xh:properties>
<!--                    <xh:variableProperty key="sensitivity" type="xsd:double" var-ref="sensEv"/>-->
                    <xh:staticProperty key="sensitivity" type="xsd:double" value="0.9"/>
                    <xh:variableProperty key="fpr" type="xsd:double" var-ref="fprEv"/>
<!--                    <xh:staticProperty key="specificity" type="xsd:double" value="0.999"/>-->
                </xh:properties>
            </xh:experiment>
        </xh:evidentialGraphs>
        <xh:properties>
<!--            <xh:staticProperty key="dValue" type="xsd:double" value="1.1"/>-->
<!--            <xh:staticProperty key="threshold" type="xsd:double" value="9.5"/>-->
<!--            <xh:variableProperty key="dValue" type="xsd:double" var-ref="dval"/>-->
        </xh:properties>
    </xh:integration>

</xh:protocol>
